[tool.poetry]
name = "battlement"
version = "0.1.0"
description = ""
authors = ["Matheus Xavier <mxavier@mail.cmdforge.com>"]

[tool.poetry.dependencies]
python = "^3.8.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
